name: meowPlugin
version: fix
api: [3.0.0-ALPHA3, 3.0.0-ALPHA4]
author: AmieXD
main: amiexd\plugin
description: "ปลั้กอินเสริม"
permissions:
  mts:
    default: false
    description: "Allows access to all features."
    children:
      mts.timeitem:
        description: Allows players to receive random items.
        default: true
      mts.command:
        default: true
        description: "Allows access to all commands."
        children:  
          mts.command.clearlag:
            default: true
            description: "Allows access to the ClearLAG"
          mts.command.buyenchant:
            default: true
            description: "Allows access to the ClearLAG"
