name: mts-plugin1
version: 1.0.5dev
api:
- 1.12.0
- 1.13.0
author: AmieXD
main: amiexd\plugin
description: "ปลั้กอินเสริม"
permissions:
  mts:
    default: false
    description: "Allows access to all MTS features."
    children:
      mts.command:
        default: true
        description: "Allows access to all MTS commands."
        children:  
          mts.command.clearlag:
            default: true
            description: "Allows access to the MtsClearlag command."
restartme:
  default: op
  children:
   restartme.command:
    default: op
    children:
     restartme.command.restartme:
      default: op

